apiVersion: v1
kind: Service
metadata:
  name: apimonedas-servicio
  namespace: apimonedas
spec:
  selector:
    app: apimonedas
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
