apiVersion: v1
kind: Service
metadata:
  name: apimonedas-servicio
  namespace: apimonedas
spec:
  selector:
    app: apimonedas
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30808  # Puerto externo para acceder a la API
  type: NodePort
